version: '3.8'

services:
  # Backend (Go)
  backend:
    build:
      context: ./Converge
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./Converge/storage:/root/storage
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - livekit

  # Frontend (React + Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
      - VITE_SERVER_URL=ws://localhost:7880
    depends_on:
      - backend
      - livekit

  # LiveKit server
  livekit:
    image: livekit/livekit-server:latest
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "7883:7883/udp"
      - "7884:7884/udp"
      - "50000-60000:50000-60000/udp"
    command:
      - livekit-server
      - --health_port=7880
    environment:
      # Test values, pls change this :)
      LIVEKIT_KEYS: "LK1234567890: abcdef1234567890abcdef1234567890"
      LIVEKIT_PROTOCOL: "http"
      LIVEKIT_INGRESS: ""
      LIVEKIT_CERT: ""
      LIVEKIT_KEY: ""

  # MySQL
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: converge_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
