services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./proxy_params:/etc/nginx/proxy_params
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - livekit
    networks:
      - converge-net


  redis:
    image: redis:7
    restart: always
    networks:
      - converge-net


  backend:
    build:
      context: ./Converge
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./Converge/storage:/root/storage
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - converge-net
    expose:
      - 8080


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
      - livekit
    networks:
       - converge-net


  livekit:
    image: livekit/livekit-server:latest
    restart: always
    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml:ro
    ports:
      - "50000-50500:50000-50500/udp"
    command: ["--config", "/etc/livekit/livekit.yaml"]
    depends_on:
      - redis
    networks:
      - converge-net
    expose:
      - 7880

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: afniseurqhweirb1203947yhqeir872314la
      MYSQL_DATABASE: converge_app
      MYSQL_USER: user
      MYSQL_PASSWORD: jsmthebest_aboba_yakov13
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d/mysql-init
    networks:
       - converge-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5


volumes:
  mysql_data:

networks:
  converge-net:
    driver: bridge
