version: '3.8'
services:

  livekit:
    image: livekit/livekit-server:latest
    restart: always
    #network_mode: host

    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
      - "7883:7883/udp"
      - "7884:7884/udp"
      # - "50000-60000:50000-60000/udp"

    command:
      - livekit-server
      - --health_port=7880
      #- --rtc.port_range_start=0
      #- --rtc.port_range_end=0
      #- --rtc.udp_port=7882

    environment:
      #Values of api key and api secret for develop, please change them in production
      LIVEKIT_KEYS: "LK1234567890: abcdef1234567890abcdef1234567890"
      LIVEKIT_PROTOCOL: "http"
      LIVEKIT_INGRESS: ""
      LIVEKIT_CERT: ""
      LIVEKIT_KEY: ""


  mysql:
    image: mysql:8.0
    restart: always
    # again values for develop, please change in production
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: converge_app
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: